remedial2/home/urls.py
from django.urls import path
from .views import (
    TeamListView, TeamDetailView, TeamCreateView, TeamUpdateView, TeamDeleteView,
    all_teams, all_owners, all_players, players_of_team, players_info_of_team,
    PlayerListView, PlayerDetailView, PlayerCreateView, PlayerUpdateView, PlayerDeleteView,
    StadiumListView, StadiumDetailView, StadiumCreateView, StadiumUpdateView, StadiumDeleteView,
    all_teams, all_owners, all_players, players_of_team, players_info_of_team,
    all_stadiums, owner_and_stadium
)

app_name = 'home'

urlpatterns = [
    # Team 
    path('teams/', TeamListView.as_view(), name='team_list'),
    path('teams/new/', TeamCreateView.as_view(), name='team_create'),
    path('teams/<int:pk>/edit/', TeamUpdateView.as_view(), name='team_update'),
    path('teams/<int:pk>/delete/', TeamDeleteView.as_view(), name='team_delete'),
    path('all-teams/', all_teams, name='all_teams'),
    path('all-owners/', all_owners, name='all_owners'),
    path('all-players/', all_players, name='all_players'),
    path('teams/<int:team_id>/players/', players_of_team, name='players_of_team'),
    path('teams/<int:team_id>/players-info/', players_info_of_team, name='players_info_of_team'),

    # Player 
    path('players/', PlayerListView.as_view(), name='player_list'),
    path('players/<int:pk>/', PlayerDetailView.as_view(), name='player_detail'),
    path('players/new/', PlayerCreateView.as_view(), name='player_create'),
    path('players/<int:pk>/edit/', PlayerUpdateView.as_view(), name='player_update'),
    path('players/<int:pk>/delete/', PlayerDeleteView.as_view(), name='player_delete'),

    # Stadium 
    path('stadiums/', StadiumListView.as_view(), name='stadium_list'),
    path('stadiums/<int:pk>/', StadiumDetailView.as_view(), name='stadium_detail'),
    path('stadiums/new/', StadiumCreateView.as_view(), name='stadium_create'),
    path('stadiums/<int:pk>/edit/', StadiumUpdateView.as_view(), name='stadium_update'),
    path('stadiums/<int:pk>/delete/', StadiumDeleteView.as_view(), name='stadium_delete'),

    #Extra Queries
    path('all-teams/', all_teams, name='all_teams'),
    path('all-owners/', all_owners, name='all_owners'),
    path('all-players/', all_players, name='all_players'),
    path('all-stadiums/', all_stadiums, name='all_stadiums'),
    path('team/<int:team_id>/players/', players_of_team, name='players_of_team'),
    path('owner-and-stadium/<str:owner_name>/', owner_and_stadium, name='owner_and_stadium'),
]

remedial2/templates/base/equipoindex.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #b80808;">
      <a class="navbar-brand" href="#"><img style="width:5rem;  margin: 0 1rem;" src="{% static 'logo_nfl.png' %}"/></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a href="{% url 'home:team_list' %}"class="nav-link text-white" >Teams</a>
          </li>
          <li class="nav-item active">
            <a href="{% url 'home:player_list' %}" class="nav-link text-white" >Players</a>
          </li>
          <li class="nav-item active" style="border-right: 1px solid #ccc; padding-right: 10px;">
            <a href="{% url 'home:stadium_list' %}" class="nav-link text-white" >Stadiums</a>
          </li>
          <div style="padding-left: 10px; display: flex;">
              <li class="nav-item active">
                <a href="{% url 'home:all_players' %}" class="nav-link text-white" >All Players</a>
              </li>
              <li class="nav-item active">
                <a href="{% url 'home:all_teams' %}" class="nav-link text-white" >All Teams</a>
              </li>
              <li class="nav-item active">
                <a href="{% url 'home:all_stadiums' %}" class="nav-link text-white" >All Stadiums</a>
              </li>
              <li class="nav-item active">
                <a href="{% url 'home:all_owners' %}" class="nav-link text-white" >All Owners</a>
              </li>
          </div>
        </ul>
      </div>
    </nav>
    <div class="container" style="margin-top: 5rem;">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
</body>
</html>